### ISSUE TITLE
bfinject: line 182 command not found

### ISSUE THREAD

**Issue by MuchiMuchiPink** [BishopFox/bfinject#6] opened 2018-01-24 08:39 UTC
Hi, I'm trying this on Electra b7 and get the error (regardless what app):

`/bootstrap/bfinject root# bash bfinject -p 481 -L decrypt
[+] Electra detected.
[+] Injecting into '/var/containers/Bundle/Application/4F70322B-9079-4490-81EA-40C4AAF12CD5/Reddit.app/Reddit'
[+] Getting Team ID from target application...
[+] Signing injectable .dylib with Team ID 2TDUX39LX8 and platform entitlements...
bfinject: line 182: 0a89bbca313be61ff6194fab53cd0e30: command not found
[+] So long and thanks for all the fish.
`

There might be as well a bug with binaries, which have spaces like 1-2-3 Tanken or DB Navigator.
Thanks for the great work.

**Comment by 0xhaggis** [comment] 2018-01-24 09:24
Ok, I can reproduce this. Fix on the way.

**Comment by 0xhaggis** [comment] 2018-01-24 09:39
Should be fixed now.

**Comment by MuchiMuchiPink** [comment] 2018-01-24 09:55
Thanks. Unfortunatley I get a new error now.
 
`/bootstrap/bfinject root# bash bfinject -p 686 -L decrypt
[+] Electra detected.
[+] Injecting into '/var/containers/Bundle/Application/4F70322B-9079-4490-81EA-40C4AAF12CD5/Reddit.app/Reddit'
[+] Getting Team ID from target application...
[+] Signing injectable .dylib with Team ID 2TDUX39LX8 and platform entitlements...
failed to get the region
2018-01-24 10:53:33.205 f12badd6f160dd61c89cc73efa33e183[718:32410] Couldn't find the address
[+] So long and thanks for all the fish.
`

**Comment by 0xhaggis** [comment] 2018-01-24 10:11
That looks like an error from `inject_criticald`: https://github.com/coolstar/electra/blob/02a93606c457efb75de32d91f874088dc2b71e21/basebinaries/inject_criticald/inject_criticald.m#L490

It's an error calling `mach_vm_region` (https://books.google.com/books?id=K8vUkpOXhN4C&pg=PA892&lpg=PA892&dq=mach_vm_region&source=bl&ots=OMilW_Zt1z&sig=06-LRoGbk7wrd73KGYyCtYTyeM4&hl=en&sa=X&ved=0ahUKEwjL97W7rfDYAhUEaq0KHcG_DhIQ6AEIMjAC#v=onepage&q=mach_vm_region&f=false ), which smells like jailbreak issues.

Perhaps try restarting the app. If that fails, try rebooting and relaunching Electra.

**Comment by MuchiMuchiPink** [comment] 2018-01-24 10:39
Neither restarting the app nor rejailbreaking works for me. Guess I have to wait for a new Electra or I give LiberiOS a try. Thanks.

**Comment by 0xhaggis** [comment] 2018-01-24 11:39
Well... `bfinject4realz` appears to work just as well on Electra as it does on LibertiOS, which means we can use to see if it throws the same error. Just replace this part of bfinject:

```
    # This is Electra
    echo "[+] Electra detected."
    cp jtool.liberios /bootstrap/usr/local/bin/
    chmod +x /bootstrap/usr/local/bin/jtool.liberios
    JTOOL=/bootstrap/usr/local/bin/jtool.liberios
    INJECTOR=/bootstrap/inject_criticald
else
```

with this:

```
    # This is Electra
    echo "[+] Electra detected."
    cp jtool.liberios /bootstrap/usr/local/bin/
    chmod +x /bootstrap/usr/local/bin/jtool.liberios
    JTOOL=/bootstrap/usr/local/bin/jtool.liberios
    cp bfinject4realz /bootstrap/usr/local/bin/
    INJECTOR=/bootstrap/usr/local/bin/bfinject4realz
else
```

Let me know how that works out.

**Comment by MuchiMuchiPink** [comment] 2018-01-24 12:03
`/bootstrap/bfinject root# bash bfinject -p 514 -L decrypt
[+] Electra detected.
[+] Injecting into '/var/containers/Bundle/Application/4F70322B-9079-4490-81EA-40C4AAF12CD5/Reddit.app/Reddit'
[+] Getting Team ID from target application...
[+] Signing injectable .dylib with Team ID 2TDUX39LX8 and platform entitlements...
[bfinject] Getting tfp.
[bfinject] Creating new remote thread
[bfinject] Failed to create thread in remote process. Is it really an App Store app?
[bfinject] thread_create() returned 4
[bfinject] errno = 2 = No such file or directory
[+] So long and thanks for all the fish.
`

**Comment by 0xhaggis** [comment] 2018-01-24 20:26
Yup, totally a jailbreak issue. If neither bfinject4realz or inject_criticald can talk to the remote process, it's out of our control. Sorry.

**Closed by 0xhaggis** 2018-01-24 20:26 UTC
